[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DDEVICE_NAME=\"esp32cam\"

[env:espcam-seeed]
platform = espressif32
board = seeed_xiao_esp32s3
# NOTE: If flashing a XIAO ESP32-C3 instead, swap the board setting below:
# board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_port = COM18
monitor_port = COM18
build_flags =
    -DBOARD_HAS_PSRAM
    -DDEVICE_NAME=\"espcam-seeed\"

[env:waveshare-esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM21
monitor_port = COM21
build_flags =
    -DDEVICE_NAME=\"waveshare-esp32\"
    -DBOARD_WAVESHARE_ESP32
lib_deps =
    adafruit/Adafruit INA219 @ ^1.2.3
    lahavg/QMI8658 @ ^1.0.1



